### ISSUE TITLE
Chrome 113 breaks typed-rest-client

### ISSUE THREAD

**Issue by WhatNot911** [microsoft/typed-rest-client#355]
### Environment
Node version: 14.16.0
Npm version: 6.14.11
OS and version: Win 10 22H2 (19045.2846)
typed-rest-client version: 1.8.9

### Issue Description
Chrome produces a TypeError: "Cannot read properties of null (reading 'getReader').
Stack traces through ```stream-http/lib/response.js``` and more importantly ```typed-rest-client/HttpClient.js``` 
This issue doesn't present itself on Firefox or Edge as of now.
I've noticed this bug before on Chrome Canary but I thought it's just a temporary bug that won't be out with the next update

### Logs

[https://user-images.githubusercontent.com/22567537/236200606-7d7295e7-4eb3-4f91-a36c-6e4844033878.png](url)

```Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getReader')
    at new push../node_modules/stream-http/lib/response.js.exports.IncomingMessage (response.js:77:1)
    at push../node_modules/stream-http/lib/request.js.ClientRequest._connect (request.js:263:1)
    at request.js:159:1
push../node_modules/stream-http/lib/response.js.exports.IncomingMessage @ response.js:77
push../node_modules/stream-http/lib/request.js.ClientRequest._connect @ request.js:263
(anonymous) @ request.js:159
Promise.then (async)
push../node_modules/stream-http/lib/request.js.ClientRequest._onFinish @ request.js:157
(anonymous) @ request.js:62
emit @ events.js:153
finishMaybe @ _stream_writable.js:630
endWritable @ _stream_writable.js:638
push../node_modules/readable-stream/lib/_stream_writable.js.Writable.end @ _stream_writable.js:594
push../node_modules/stream-http/lib/request.js.ClientRequest.end @ request.js:297
requestRawWithCallback @ HttpClient.js:330
(anonymous) @ HttpClient.js:280
requestRaw @ HttpClient.js:273
(anonymous) @ HttpClient.js:205
(anonymous) @ HttpClient.js:9
push.../../PROJECTNAME/node_modules/typed-rest-client/HttpClient.js.__awaiter @ HttpClient.js:5
request @ HttpClient.js:194
get @ HttpClient.js:168
(anonymous) @ RestClient.js:52
(anonymous) @ RestClient.js:9
push.../../PROJECTNAME/node_modules/typed-rest-client/RestClient.js.__awaiter @ RestClient.js:5
get @ RestClient.js:50
_callee3$ @ oidc-storage-store.ts:67
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
RestoreStorage @ oidc-storage-store.ts:57
_callee$ @ modified-web-sale-user-identity.ts:99
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
Initialize @ modified-web-sale-user-identity.ts:96
_callee$ @ initializer.ts:92
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
InitializeAsync @ initializer.ts:24
_callee$ @ cjs.js:103
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
mounted @ cjs.js:99
invokeWithErrorHandling @ vue.esm.js:1863
callHook @ vue.esm.js:4228
insert @ vue.esm.js:3148
invokeInsertHook @ vue.esm.js:6357
patch @ vue.esm.js:6576
Vue._update @ vue.esm.js:3954
updateComponent @ vue.esm.js:4075
get @ vue.esm.js:4488
Watcher @ vue.esm.js:4477
mountComponent @ vue.esm.js:4082
push../node_modules/vue/dist/vue.esm.js.Vue.$mount @ vue.esm.js:9063
push../node_modules/vue/dist/vue.esm.js.Vue.$mount @ vue.esm.js:11974
(anonymous) @ web-sale-main.ts:81
./src/web-sale/web-sale-main.ts @ app.js:59255
__webpack_require__ @ bootstrap:848
fn @ bootstrap:150
1 @ app.js:59268
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
(anonymous) @ bootstrap:924
(anonymous) @ bootstrap:924```

![logs](https://user-images.githubusercontent.com/22567537/236200606-7d7295e7-4eb3-4f91-a36c-6e4844033878.png)

**Comment by DenisRumyantsev** [comment]
Hi @WhatNot911, thanks for reporting this issue! Let us take a look at it

**Comment by jpvillaseca** [comment]
A very similar issue started popping out with Chromium 113 in other repos, such as https://github.com/godotengine/godot/issues/76825

The signature of the response.body now is null instead of a ReadableStream
![image](https://user-images.githubusercontent.com/9826460/236884193-becc0b85-1d38-4c01-acbd-e95b03fa2947.png)

**Comment by WhatNot911** [comment]
Everything seems to be back to normal as of 113.0.5672.93

**Comment by WhatNot911** [comment]
![Screenshot of a commit that reverts back breaking change](https://user-images.githubusercontent.com/22567537/237027778-49968f99-9c6b-420d-9adb-0b362710b338.png)

Commit 135354b7bdb554cd03c913af7c90aceead03c4d4 reverts breaking change, but as been mentioned in a third party topic - apparently the breaking change is trying to comply with fetch standards .
