### ISSUE TITLE
Error in running samples

### ISSUE THREAD

**Issue by djKooks** [Microsoft/typed-rest-client#38]
Hello.
While following on contributing guide, I had an error in `npm run samples`.
```
> typed-rest-client@1.0.1 samples /Users/kwangin/workspace/github_source/typed-rest-client
> node make.js samples

> /Users/kwangin/workspace/github_source/typed-rest-client/node_modules/.bin/tsc --outDir /Users/kwangin/workspace/github_source/typed-rest-client/_build
/Users/kwangin/workspace/github_source/typed-rest-client/samples /Users/kwangin/workspace/github_source/typed-rest-client
> node samples.js
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/kwangin/workspace/github_source/typed-rest-client/samples/samples.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
/Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/src/common.js:381
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/src/common.js:112:27)
    at _exec (/Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/src/exec.js:292:12)
    at /Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/src/common.js:316:23
    at run (/Users/kwangin/workspace/github_source/typed-rest-client/make.js:14:14)
    at Function.target.samples (/Users/kwangin/workspace/github_source/typed-rest-client/make.js:51:5)
    at Object.global.target.(anonymous function) [as samples] (/Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/make.js:36:40)
    at /Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/make.js:48:27
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/Users/kwangin/workspace/github_source/typed-rest-client/node_modules/shelljs/make.js:46:10)
    at ontimeout (timers.js:469:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typed-rest-client@1.0.1 samples: `node make.js samples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typed-rest-client@1.0.1 samples script.
```
Am I doing something wrong?
My node version is `v8.3.0`, and npm is `5.5.1`.
Thanks.

**Comment by stephenmichaelf** [comment]
@djKooks Your node and npm versions look good. What OS are you running? Were you able to run build and test without issue?

**Comment by djKooks** [comment]
@stephenmichaelf Oh, I'm working it on Mac, Sierra. Is it only works on Linux?
Test `npm test` works find.

**Comment by stephenmichaelf** [comment]
@djKooks It should work on Mac. It looks like it cant find the transpiled samples.js file. If you browse to:

/Users/kwangin/workspace/github_source/typed-rest-client/samples

Do you see samples.js?

**Comment by stephenmichaelf** [comment]
Also, have you pulled latest off master?

**Comment by djKooks** [comment]
@stephenmichaelf I'm working in latest version, but cannot find `sample.js` in /samples. There are only `sample.ts`.

**Comment by djKooks** [comment]
@stephenmichaelf Hello.
It was just a problem that `sample.ts` is not being compiled js before running `node sample.js`. I added `tsc` before running this in #40 .

Maybe if you have better solution or work I did is not fit in project concept, don't hesitate to tell.

Thanks.

**Comment by bryanmacfarlane** [comment]
This is fixed in a separate set of changes I have locally (fixing a couple other path bugs as well).  This will go in this morning.

**Comment by bryanmacfarlane** [comment]
fixed with https://github.com/Microsoft/typed-rest-client/commit/68d80682d313817f4db185464686896119b9f5c1
